# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

main:
  - name: About me
    url: /
    weight: 10
  - name: Skills
    parent: About me
    url: /#skills
  - name: Archiving
    url: /#archiving
    parent: About me
  - name: Skill
    url: /#skills
    weight: 13
  - name: Archive
    url: /#archiving
    weight: 16
  - name: Projects
    url: /#projects
    weight: 18
  - name: Career
    url: /#careers
    weight: 20
  - name: Contact
    url: /#contact
    weight: 24
