# SITE SETUP
# Guide: https://docs.hugoblox.com/tutorial/
# Documentation: https://docs.hugoblox.com/
# This file is formatted using YAML syntax - learn more at https://learnxinyminutes.com/docs/yaml/

# Appearance
appearance:
  mode: system
  color: emerald

# SEO
marketing:
  seo:
    site_type: Person
    local_business_type: ""
    org_name: ""
    description: "The highly-customizable Hugo Academic theme powered by Hugo Blox Builder. Easily create your personal academic website."
    twitter: "GetResearchDev"
  analytics:
    google_analytics: ""
    baidu_tongji: ""
    plausible: ""
    fathom: ""
    pirsch: ""
  verification:
    google: ""
    baidu: ""

# Site header
header:
  navbar:
    enable: true
    blox: "navbar"
    fixed_to_top: true
    show_search: true
    show_theme_chooser: true
    logo:
      text: "KJH's Portfolio"
      filename: "logo.jpg"
        show_language: true
    show_day_night: true
    show_search: true
    show_theme_chooser: true
    show_translations: true
    button:
      enable: true
      text: "kkkkimjehyeon"
      url: "https://dlsrks0631.github.io/"

# Site footer
footer:
  copyright:
    notice: "© {year} Me. This work is licensed under {license}"
    license:
      enable: true
      allow_derivatives: false
      share_alike: true
      allow_commercial: false

# Localization
locale:
  date_format: "Jan 2, 2006"
  time_format: "3:04 PM"

features:
  syntax_highlighter:
    enable: true
    extra_languages:
      - r
      - latex
  math:
    enable: false
  privacy_pack:
    enable: false
  repository:
    url: 'https://github.com/dlsrks0631/dlsrks0631.github.io'
    branch: main
  avatar:
    gravatar: false
    shape: circle
  comment:
    provider: ''
    disqus:
      shortname: ''
      show_count: true
    commento:
      url: ''
    giscus:
      repo: ''
      repo_id: ''
      category: ''
      category_id: ''
  search:
    provider: wowchemy
  map:
    provider: 'mapnik'
    api_key: ''
    zoom: 15

# Site features
# features:
#   math:
#     enable: false
#   privacy_pack:
#     enable: false

ogImage: "assets/media/logo.jpg"
